name: lovely_di
description: A dependency injection library what guarantees compile-time errors instead of runtime errors.
repository: https://github.com/eboshare/lovely_di
issue_tracker: https://github.com/eboshare/lovely_di/issues

version: 0.5.0-dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
